---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.7
    driver_config:
      require_chef_omnibus: false
      provision_command:
        - apt-get update; apt-get -y install build-essential wget net-tools
        - curl -L https://www.opscode.com/chef/install.sh | bash
