---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: chef/debian-7.7
    platform: debian
    driver_config:
      provision_command:
        - apt-get -y install build-essential

suites:
  - name: default
    run_list:
      - recipe[simple-mailcatcher-test]
    attributes:

