name            "silex-demo"
maintainer      "Johan Lerche Schulz"
license         "Copyright 2015 Johan Lerche Schulz"
description     "Company specific recipes"
version         "0.1"
supports        "ubuntu"
